import type { DesignerTestCase } from '../core/types'

/**
 * 用例 3：由旧设计器的“配货单”结构转换而来。
 * 原模板为 210 × 134 mm，并使用像素坐标；这里已换算为 Hiprint 的点坐标。
 */
export const deliveryOrderCase: DesignerTestCase = {
  id: 'delivery-order',
  name: '配货单测试单据',
  description: '验证非标准纸张、单据头、商品明细表、备注和合计区域。',
  template: {
    panels: [{
      index: 0,
      name: '配货单',
      width: 210,
      height: 134,
      paperHeader: 74,
      paperFooter: 288,
      printElements: [
        {
          options: {
            left: 0,
            top: 0,
            width: 595,
            height: 30,
            title: '配货单',
            fontFamily: '黑体',
            fontSize: 22,
            fontWeight: '700',
            textAlign: 'center',
            lineHeight: 28,
            hideTitle: true,
          },
          printElementType: { title: '配货单标题', type: 'text' },
        },
        {
          options: {
            left: 2,
            top: 34,
            width: 132,
            height: 18,
            field: 'billno',
            title: '单号',
            testData: 'PH202609040001',
            fontSize: 10,
          },
          printElementType: { title: '单号', type: 'text' },
        },
        {
          options: {
            left: 137,
            top: 34,
            width: 166,
            height: 18,
            field: 'storeName',
            title: '收货店铺',
            testData: '杭州湖滨旗舰店',
            fontSize: 10,
          },
          printElementType: { title: '收货店铺', type: 'text' },
        },
        {
          options: {
            left: 305,
            top: 34,
            width: 92,
            height: 18,
            field: 'wareName',
            title: '仓库',
            testData: '华东中心仓',
            fontSize: 10,
          },
          printElementType: { title: '仓库', type: 'text' },
        },
        {
          options: {
            left: 399,
            top: 34,
            width: 194,
            height: 18,
            field: 'createTime',
            title: '创建时间',
            testData: '2026-09-04 10:28',
            fontSize: 10,
          },
          printElementType: { title: '创建时间', type: 'text' },
        },
        {
          options: {
            left: 2,
            top: 54,
            width: 590,
            height: 18,
            field: 'remark',
            title: '备注',
            testData: '请复核颜色、尺码和数量后发货。',
            fontSize: 10,
          },
          printElementType: { title: '备注', type: 'text' },
        },
        {
          options: {
            left: 2,
            top: 78,
            width: 590,
            height: 205,
            field: 'items',
            fields: [
              { text: '货号', field: 'commCode' },
              { text: '商品名称', field: 'commName' },
              { text: '颜色', field: 'color' },
              { text: '尺码', field: 'size' },
              { text: '小计', field: 'numTotal' },
              { text: '指导价', field: 'price' },
              { text: '指导总价', field: 'priceTotal' },
            ],
            columns: [[
              { title: '货号', field: 'commCode', width: 84, align: 'left' },
              { title: '商品名称', field: 'commName', width: 106, align: 'left' },
              { title: '颜色', field: 'color', width: 55, align: 'center' },
              { title: '尺码', field: 'size', width: 55, align: 'center' },
              { title: '小计', field: 'numTotal', width: 60, align: 'center' },
              { title: '指导价', field: 'price', width: 75, align: 'right' },
              { title: '指导总价', field: 'priceTotal', width: 85, align: 'right' },
            ]],
          },
          printElementType: {
            title: '配货商品明细',
            type: 'table',
            editable: true,
            columnDisplayEditable: true,
            columnResizable: true,
          },
        },
        {
          options: {
            left: 355,
            top: 294,
            width: 237,
            height: 20,
            field: 'totalText',
            title: '合计',
            testData: '合计：5 件 / ¥ 1,595.00',
            fontSize: 11,
            fontWeight: '700',
            textAlign: 'right',
            hideTitle: true,
          },
          printElementType: { title: '单据合计', type: 'text' },
        },
      ],
    }],
  },
  data: {
    billno: 'PH202609040001',
    storeName: '杭州湖滨旗舰店',
    wareName: '华东中心仓',
    createTime: '2026-09-04 10:28',
    remark: '请复核颜色、尺码和数量后发货。',
    items: [
      { commCode: 'JK-2026', commName: '轻量连帽夹克', color: '黑色', size: 'M', numTotal: 2, price: '399.00', priceTotal: '798.00' },
      { commCode: 'TS-2026', commName: '纯棉基础 T 恤', color: '白色', size: 'L', numTotal: 2, price: '199.00', priceTotal: '398.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
      { commCode: 'BG-2026', commName: '城市通勤双肩包', color: '灰色', size: '均码', numTotal: 1, price: '399.00', priceTotal: '399.00' },
    ],
    totalText: '合计：5 件 / ¥ 1,595.00',
  },
  assertions: [
    '画布纸张尺寸应为 210 × 134 mm。',
    '单号、收货店铺、仓库、创建时间和备注应显示对应测试数据。',
    '商品明细表应显示 3 行数据和 7 个字段列。',
    '底部应显示“合计：5 件 / ¥ 1,595.00”。',
  ],
}
